const shopMenuData = [
  {
    id: 1,
    title: "Product Types",
    link: "/shop/types",
    hot: false,
    trending: true,
    sale: false,
    children: [
      {
        id: 11,
        title: "Simple Product",
        link: "/shop/simple-product",
        hot: false,
        trending: false,
        sale: false,
      },
      {
        id: 12,
        title: "Products",
        link: "/shop/products",
        hot: true,
        trending: false,
        sale: false,
      },
      {
        id: 13,
        title: "External/Affiliate Products",
        link: "/shop/external-affiliate-products",
        hot: false,
        trending: false,
        sale: false,
      },
      {
        id: 14,
        title: "Variable Products",
        link: "/shop/variable-products",
        hot: false,
        trending: true,
        sale: false,
      },
      {
        id: 15,
        title: "Sale Products",
        link: "/shop/sale-products",
        hot: false,
        trending: false,
        sale: true,
      },
      {
        id: 16,
        title: "Up Sale Products",
        link: "/shop/up-sale-products",
        hot: false,
        trending: false,
        sale: false,
      },
    ],
  },

  {
    id: 2,
    title: "WooCommerce Pages",
    link: "/shop/pages",
    hot: true,
    trending: false,
    sale: false,
    children: [
      {
        id: 21,
        title: "Shop Page",
        link: "/shop/shop-page",
        hot: false,
        trending: false,
        sale: false,
      },
      {
        id: 22,
        title: "Checkout Page",
        link: "/shop/checkout",
        hot: false,
        trending: true,
        sale: false,
      },
      {
        id: 23,
        title: "My Account",
        link: "/shop/my-account",
        hot: false,
        trending: false,
        sale: false,
      },
      {
        id: 24,
        title: "Category Page",
        link: "/shop/category",
        hot: false,
        trending: false,
        sale: false,
      },
      {
        id: 25,
        title: "Shop Ajax Filter",
        link: "/shop/ajax-filter",
        hot: false,
        trending: false,
        sale: false,
      },
      {
        id: 26,
        title: "Privacy",
        link: "/shop/privacy",
        hot: false,
        trending: false,
        sale: false,
      },
    ],
  },

  {
    id: 3,
    title: "Product Feature",
    link: "/shop/features",
    hot: false,
    trending: false,
    sale: false,
    children: [
      {
        id: 31,
        title: "Stock Progress Bar",
        link: "/shop/stock-progress",
        hot: false,
        trending: true,
        sale: false,
      },
      {
        id: 32,
        title: "Product Bar",
        link: "/shop/product-bar",
        hot: false,
        trending: false,
        sale: false,
      },
      {
        id: 33,
        title: "Countdown Feature",
        link: "/shop/countdown",
        hot: true,
        trending: false,
        sale: false,
      },
      {
        id: 34,
        title: "Size Guide Table",
        link: "/shop/size-guide",
        hot: false,
        trending: false,
        sale: false,
      },
    ],
  },
];

export default shopMenuData;
